class CountryInfo {
  final String name;
  final String code;
  final String dialCode;
  final String currency;
  final String currencySymbol;
  final String flag;

  const CountryInfo({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.currency,
    required this.currencySymbol,
    required this.flag,
  });
}

class CountryConstants {
  static const List<CountryInfo> countries = [
    CountryInfo(name: "Afghanistan", code: "AF", dialCode: "+93", currency: "AFN", currencySymbol: "؋", flag: "🇦🇫"),
    CountryInfo(name: "Albania", code: "AL", dialCode: "+355", currency: "ALL", currencySymbol: "L", flag: "🇦🇱"),
    CountryInfo(name: "Algeria", code: "DZ", dialCode: "+213", currency: "DZD", currencySymbol: "د.ج", flag: "🇩🇿"),
    CountryInfo(name: "Andorra", code: "AD", dialCode: "+376", currency: "EUR", currencySymbol: "€", flag: "🇦🇩"),
    CountryInfo(name: "Angola", code: "AO", dialCode: "+244", currency: "AOA", currencySymbol: "Kz", flag: "🇦🇴"),
    CountryInfo(name: "Argentina", code: "AR", dialCode: "+54", currency: "ARS", currencySymbol: r"$", flag: "🇦🇷"),
    CountryInfo(name: "Armenia", code: "AM", dialCode: "+374", currency: "AMD", currencySymbol: "֏", flag: "🇦🇲"),
    CountryInfo(name: "Australia", code: "AU", dialCode: "+61", currency: "AUD", currencySymbol: r"$", flag: "🇦🇺"),
    CountryInfo(name: "Austria", code: "AT", dialCode: "+43", currency: "EUR", currencySymbol: "€", flag: "🇦🇹"),
    CountryInfo(name: "Azerbaijan", code: "AZ", dialCode: "+994", currency: "AZN", currencySymbol: "₼", flag: "🇦🇿"),
    CountryInfo(name: "Bahrain", code: "BH", dialCode: "+973", currency: "BHD", currencySymbol: ".د.ب", flag: "🇧🇭"),
    CountryInfo(name: "Bangladesh", code: "BD", dialCode: "+880", currency: "BDT", currencySymbol: "৳", flag: "🇧🇩"),
    CountryInfo(name: "Belarus", code: "BY", dialCode: "+375", currency: "BYN", currencySymbol: "Br", flag: "🇧🇾"),
    CountryInfo(name: "Belgium", code: "BE", dialCode: "+32", currency: "EUR", currencySymbol: "€", flag: "🇧🇪"),
    CountryInfo(name: "Bhutan", code: "BT", dialCode: "+975", currency: "BTN", currencySymbol: "Nu.", flag: "🇧🇹"),
    CountryInfo(name: "Bolivia", code: "BO", dialCode: "+591", currency: "BOB", currencySymbol: "Bs.", flag: "🇧🇴"),
    CountryInfo(name: "Botswana", code: "BW", dialCode: "+267", currency: "BWP", currencySymbol: "P", flag: "🇧🇼"),
    CountryInfo(name: "Brazil", code: "BR", dialCode: "+55", currency: "BRL", currencySymbol: r"R$", flag: "🇧🇷"),
    CountryInfo(name: "Bulgaria", code: "BG", dialCode: "+359", currency: "BGN", currencySymbol: "лв", flag: "🇧🇬"),
    CountryInfo(name: "Cambodia", code: "KH", dialCode: "+855", currency: "KHR", currencySymbol: "៛", flag: "🇰🇭"),
    CountryInfo(name: "Cameroon", code: "CM", dialCode: "+237", currency: "XAF", currencySymbol: "Fr", flag: "🇨🇲"),
    CountryInfo(name: "Canada", code: "CA", dialCode: "+1", currency: "CAD", currencySymbol: r"$", flag: "🇨🇦"),
    CountryInfo(name: "Chile", code: "CL", dialCode: "+56", currency: "CLP", currencySymbol: r"$", flag: "🇨🇱"),
    CountryInfo(name: "China", code: "CN", dialCode: "+86", currency: "CNY", currencySymbol: "¥", flag: "🇨🇳"),
    CountryInfo(name: "Colombia", code: "CO", dialCode: "+57", currency: "COP", currencySymbol: r"$", flag: "🇨🇴"),
    CountryInfo(name: "Croatia", code: "HR", dialCode: "+385", currency: "EUR", currencySymbol: "€", flag: "🇭🇷"),
    CountryInfo(name: "Cuba", code: "CU", dialCode: "+53", currency: "CUP", currencySymbol: r"$", flag: "🇨🇺"),
    CountryInfo(name: "Cyprus", code: "CY", dialCode: "+357", currency: "EUR", currencySymbol: "€", flag: "🇨🇾"),
    CountryInfo(name: "Czech Republic", code: "CZ", dialCode: "+420", currency: "CZK", currencySymbol: "Kč", flag: "🇨🇿"),
    CountryInfo(name: "Denmark", code: "DK", dialCode: "+45", currency: "DKK", currencySymbol: "kr", flag: "🇩🇰"),
    CountryInfo(name: "Egypt", code: "EG", dialCode: "+20", currency: "EGP", currencySymbol: "E£", flag: "🇪🇬"),
    CountryInfo(name: "Estonia", code: "EE", dialCode: "+372", currency: "EUR", currencySymbol: "€", flag: "🇪🇪"),
    CountryInfo(name: "Ethiopia", code: "ET", dialCode: "+251", currency: "ETB", currencySymbol: "Br", flag: "🇪🇹"),
    CountryInfo(name: "Finland", code: "FI", dialCode: "+358", currency: "EUR", currencySymbol: "€", flag: "🇫🇮"),
    CountryInfo(name: "France", code: "FR", dialCode: "+33", currency: "EUR", currencySymbol: "€", flag: "🇫🇷"),
    CountryInfo(name: "Georgia", code: "GE", dialCode: "+995", currency: "GEL", currencySymbol: "₾", flag: "🇬🇪"),
    CountryInfo(name: "Germany", code: "DE", dialCode: "+49", currency: "EUR", currencySymbol: "€", flag: "🇩🇪"),
    CountryInfo(name: "Ghana", code: "GH", dialCode: "+233", currency: "GHS", currencySymbol: "₵", flag: "🇬🇭"),
    CountryInfo(name: "Greece", code: "GR", dialCode: "+30", currency: "EUR", currencySymbol: "€", flag: "🇬🇷"),
    CountryInfo(name: "Hong Kong", code: "HK", dialCode: "+852", currency: "HKD", currencySymbol: r"$", flag: "🇭🇰"),
    CountryInfo(name: "Hungary", code: "HU", dialCode: "+36", currency: "HUF", currencySymbol: "Ft", flag: "🇭🇺"),
    CountryInfo(name: "Iceland", code: "IS", dialCode: "+354", currency: "ISK", currencySymbol: "kr", flag: "🇮🇸"),
    CountryInfo(name: "India", code: "IN", dialCode: "+91", currency: "INR", currencySymbol: "₹", flag: "🇮🇳"),
    CountryInfo(name: "Indonesia", code: "ID", dialCode: "+62", currency: "IDR", currencySymbol: "Rp", flag: "🇮🇩"),
    CountryInfo(name: "Iran", code: "IR", dialCode: "+98", currency: "IRR", currencySymbol: "﷼", flag: "🇮🇷"),
    CountryInfo(name: "Iraq", code: "IQ", dialCode: "+964", currency: "IQD", currencySymbol: "ع.د", flag: "🇮🇶"),
    CountryInfo(name: "Ireland", code: "IE", dialCode: "+353", currency: "EUR", currencySymbol: "€", flag: "🇮🇪"),
    CountryInfo(name: "Israel", code: "IL", dialCode: "+972", currency: "ILS", currencySymbol: "₪", flag: "🇮🇱"),
    CountryInfo(name: "Italy", code: "IT", dialCode: "+39", currency: "EUR", currencySymbol: "€", flag: "🇮🇹"),
    CountryInfo(name: "Jamaica", code: "JM", dialCode: "+1", currency: "JMD", currencySymbol: r"$", flag: "🇯🇲"),
    CountryInfo(name: "Japan", code: "JP", dialCode: "+81", currency: "JPY", currencySymbol: "¥", flag: "🇯🇵"),
    CountryInfo(name: "Jordan", code: "JO", dialCode: "+962", currency: "JOD", currencySymbol: "د.ا", flag: "🇯🇴"),
    CountryInfo(name: "Kazakhstan", code: "KZ", dialCode: "+7", currency: "KZT", currencySymbol: "₸", flag: "🇰🇿"),
    CountryInfo(name: "Kenya", code: "KE", dialCode: "+254", currency: "KES", currencySymbol: "Sh", flag: "🇰🇪"),
    CountryInfo(name: "Kuwait", code: "KW", dialCode: "+965", currency: "KWD", currencySymbol: "د.ك", flag: "🇰🇼"),
    CountryInfo(name: "Latvia", code: "LV", dialCode: "+371", currency: "EUR", currencySymbol: "€", flag: "🇱🇻"),
    CountryInfo(name: "Lebanon", code: "LB", dialCode: "+961", currency: "LBP", currencySymbol: "ل.ل", flag: "🇱🇧"),
    CountryInfo(name: "Libya", code: "LY", dialCode: "+218", currency: "LYD", currencySymbol: "ل.د", flag: "🇱🇾"),
    CountryInfo(name: "Lithuania", code: "LT", dialCode: "+370", currency: "EUR", currencySymbol: "€", flag: "🇱🇹"),
    CountryInfo(name: "Luxembourg", code: "LU", dialCode: "+352", currency: "EUR", currencySymbol: "€", flag: "🇱🇺"),
    CountryInfo(name: "Malaysia", code: "MY", dialCode: "+60", currency: "MYR", currencySymbol: "RM", flag: "🇲🇾"),
    CountryInfo(name: "Maldives", code: "MV", dialCode: "+960", currency: "MVR", currencySymbol: ".ރ", flag: "🇲🇻"),
    CountryInfo(name: "Malta", code: "MT", dialCode: "+356", currency: "EUR", currencySymbol: "€", flag: "🇲🇹"),
    CountryInfo(name: "Mauritius", code: "MU", dialCode: "+230", currency: "MUR", currencySymbol: "₨", flag: "🇲🇺"),
    CountryInfo(name: "Mexico", code: "MX", dialCode: "+52", currency: "MXN", currencySymbol: r"$", flag: "🇲🇽"),
    CountryInfo(name: "Monaco", code: "MC", dialCode: "+377", currency: "EUR", currencySymbol: "€", flag: "🇲🇨"),
    CountryInfo(name: "Mongolia", code: "MN", dialCode: "+976", currency: "MNT", currencySymbol: "₮", flag: "🇲🇳"),
    CountryInfo(name: "Morocco", code: "MA", dialCode: "+212", currency: "MAD", currencySymbol: "د.م.", flag: "🇲🇦"),
    CountryInfo(name: "Myanmar", code: "MM", dialCode: "+95", currency: "MMK", currencySymbol: "Ks", flag: "🇲🇲"),
    CountryInfo(name: "Namibia", code: "NA", dialCode: "+264", currency: "NAD", currencySymbol: r"$", flag: "🇳🇦"),
    CountryInfo(name: "Nepal", code: "NP", dialCode: "+977", currency: "NPR", currencySymbol: "₨", flag: "🇳🇵"),
    CountryInfo(name: "Netherlands", code: "NL", dialCode: "+31", currency: "EUR", currencySymbol: "€", flag: "🇳🇱"),
    CountryInfo(name: "New Zealand", code: "NZ", dialCode: "+64", currency: "NZD", currencySymbol: r"$", flag: "🇳🇿"),
    CountryInfo(name: "Nigeria", code: "NG", dialCode: "+234", currency: "NGN", currencySymbol: "₦", flag: "🇳🇬"),
    CountryInfo(name: "Norway", code: "NO", dialCode: "+47", currency: "NOK", currencySymbol: "kr", flag: "🇳🇴"),
    CountryInfo(name: "Oman", code: "OM", dialCode: "+968", currency: "OMR", currencySymbol: "ر.ع.", flag: "🇴🇲"),
    CountryInfo(name: "Pakistan", code: "PK", dialCode: "+92", currency: "PKR", currencySymbol: "₨", flag: "🇵🇰"),
    CountryInfo(name: "Panama", code: "PA", dialCode: "+507", currency: "PAB", currencySymbol: "B/.", flag: "🇵🇦"),
    CountryInfo(name: "Peru", code: "PE", dialCode: "+51", currency: "PEN", currencySymbol: "S/.", flag: "🇵🇪"),
    CountryInfo(name: "Philippines", code: "PH", dialCode: "+63", currency: "PHP", currencySymbol: "₱", flag: "🇵🇭"),
    CountryInfo(name: "Poland", code: "PL", dialCode: "+48", currency: "PLN", currencySymbol: "zł", flag: "🇵🇱"),
    CountryInfo(name: "Portugal", code: "PT", dialCode: "+351", currency: "EUR", currencySymbol: "€", flag: "🇵🇹"),
    CountryInfo(name: "Qatar", code: "QA", dialCode: "+974", currency: "QAR", currencySymbol: "ر.ق", flag: "🇶🇦"),
    CountryInfo(name: "Romania", code: "RO", dialCode: "+40", currency: "RON", currencySymbol: "lei", flag: "🇷🇴"),
    CountryInfo(name: "Russia", code: "RU", dialCode: "+7", currency: "RUB", currencySymbol: "₽", flag: "🇷🇺"),
    CountryInfo(name: "Saudi Arabia", code: "SA", dialCode: "+966", currency: "SAR", currencySymbol: "ر.س", flag: "🇸🇦"),
    CountryInfo(name: "Singapore", code: "SG", dialCode: "+65", currency: "SGD", currencySymbol: r"$", flag: "🇸🇬"),
    CountryInfo(name: "Slovakia", code: "SK", dialCode: "+421", currency: "EUR", currencySymbol: "€", flag: "🇸🇰"),
    CountryInfo(name: "Slovenia", code: "SI", dialCode: "+386", currency: "EUR", currencySymbol: "€", flag: "🇸🇮"),
    CountryInfo(name: "South Africa", code: "ZA", dialCode: "+27", currency: "ZAR", currencySymbol: "R", flag: "🇿🇦"),
    CountryInfo(name: "South Korea", code: "KR", dialCode: "+82", currency: "KRW", currencySymbol: "₩", flag: "🇰🇷"),
    CountryInfo(name: "Spain", code: "ES", dialCode: "+34", currency: "EUR", currencySymbol: "€", flag: "🇪🇸"),
    CountryInfo(name: "Sri Lanka", code: "LK", dialCode: "+94", currency: "LKR", currencySymbol: "Rs", flag: "🇱🇰"),
    CountryInfo(name: "Sweden", code: "SE", dialCode: "+46", currency: "SEK", currencySymbol: "kr", flag: "🇸🇪"),
    CountryInfo(name: "Switzerland", code: "CH", dialCode: "+41", currency: "CHF", currencySymbol: "CHF", flag: "🇨🇭"),
    CountryInfo(name: "Taiwan", code: "TW", dialCode: "+886", currency: "TWD", currencySymbol: r"NT$", flag: "🇹🇼"),
    CountryInfo(name: "Thailand", code: "TH", dialCode: "+66", currency: "THB", currencySymbol: "฿", flag: "🇹🇭"),
    CountryInfo(name: "Turkey", code: "TR", dialCode: "+90", currency: "TRY", currencySymbol: "₺", flag: "🇹🇷"),
    CountryInfo(name: "Ukraine", code: "UA", dialCode: "+380", currency: "UAH", currencySymbol: "₴", flag: "🇺🇦"),
    CountryInfo(name: "United Arab Emirates", code: "AE", dialCode: "+971", currency: "AED", currencySymbol: "د.إ", flag: "🇦🇪"),
    CountryInfo(name: "United Kingdom", code: "GB", dialCode: "+44", currency: "GBP", currencySymbol: "£", flag: "🇬🇧"),
    CountryInfo(name: "United States", code: "US", dialCode: "+1", currency: "USD", currencySymbol: r"$", flag: "🇺🇸"),
    CountryInfo(name: "Uruguay", code: "UY", dialCode: "+598", currency: "UYU", currencySymbol: r"$U", flag: "🇺🇾"),
    CountryInfo(name: "Uzbekistan", code: "UZ", dialCode: "+998", currency: "UZS", currencySymbol: "so'm", flag: "🇺🇿"),
    CountryInfo(name: "Venezuela", code: "VE", dialCode: "+58", currency: "VES", currencySymbol: "Bs.S", flag: "🇻🇪"),
    CountryInfo(name: "Vietnam", code: "VN", dialCode: "+84", currency: "VND", currencySymbol: "₫", flag: "🇻🇳"),
    CountryInfo(name: "Zimbabwe", code: "ZW", dialCode: "+263", currency: "ZWL", currencySymbol: r"$", flag: "🇿🇼"),
  ];
}
